services:
  database:
    image: postgres:14.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: earendil
      POSTGRES_PASSWORD: earendil
      POSTGRES_DB: earendil
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  api:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
    depends_on:
      - database